version: '3.9'

services:
  go-app:
    container_name: go-app
    image: golang:1.21
    volumes:
      - .:/go/src/management-personal
    ports:
      - 8080:8080
    command: sh -c "cd /go/src/management-personal && go run main.go"

  mysql:
    container_name: mysql8
    image: mysql:8
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "management-personal"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "dev"
