version: '3.8'

services:
  app:
    build:
      context: docker
      dockerfile: ./docker/Dockerfile
    container_name: go_app
    ports:
      - "8080:8080"
    restart: always
    networks:
      - golandia
    volumes:
      - ../:/app

networks:
  golandia:
    name: app
    driver: bridge